# Generated by Django 4.1.5 on 2023-01-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decrees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default=1, max_length=7, verbose_name="Цвет в HEX"),
            preserve_default=False,
        ),
    ]
