# Generated by Django 4.1.5 on 2023-01-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decrees", "0002_category_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Executor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ФИО")),
            ],
            options={
                "verbose_name": "Исполнитель",
                "verbose_name_plural": "Исполнители",
            },
        ),
    ]
