# Generated by Django 4.1.5 on 2023-01-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("decrees", "0004_documents"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documents",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "Документ",
                "verbose_name_plural": "Список документов",
            },
        ),
    ]
